# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        GOARCH: ${{ matrix.goarch }}

    - name: Build for ${{ matrix.goarch }}
      run: GOOS=darwin go build -o ${{ matrix.goarch }}/cp-connect main.go
      env:
        GOARCH= ${{ matrix.goarch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: cp-connect
        path: $(goarch)/cp-connect
