# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          architecture: ${{ matrix.goarch }}

      - name: Build for ${{ matrix.goarch }}
        run: go build -ldflags "$LDFLAGS" -o cp-connect-${{ matrix.goarch }} main.go
        env:
          LDFLAGS: -X main.version=${{ github.ref }} -X main.commit=${{ github.sha }}
          GOOS: macos-latest
          GOARCH: ${{ matrix.goarch }}

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --no-tty

      - name: Sign artifact
        run: |
          gpg --batch --detach-sig --armor --output cp-connect-${{ matrix.goarch }}.asc cp-connect-${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cp-connect
          path: cp-connect-${{ matrix.goarch }}*
