# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ arm64 ]
#        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Prepare output directories
        run: mkdir ${{ matrix.goarch }}

      - name: Build for ${{ matrix.goarch }}
        run: go build -ldflags "$LDFLAGS" -o ${{ matrix.goarch }}/cp-connect main.go
        env:
          LDFLAGS: -X main.version=${{ github.ref }} -X main.commit=${{ github.sha }}
          GOOS: darwin
          GOARCH: ${{ matrix.goarch }}

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --no-tty

      - name: List Secret Keys (Debug)
        run: gpg --list-secret-keys --keyid-format long

      - name: Sign artifact
        run: |
          gpg --batch --no-tty --detach-sig --armor --output ${{ matrix.goarch }}/cp-connect.asc ${{ matrix.goarch }}/cp-connect

      - name: List Artifacts (Debug)
        run: find .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cp-connect-${{ matrix.goarch }}
          path: ${{ matrix.goarch }}/cp-connect*
